### ISSUE TITLE
Allow using ssh-agent inside WSL from wslgit

### ISSUE THREAD

**Issue by rigarash** [andy-5/wslgit#16] opened 2018-01-20 06:13 UTC
Even if I make ssh-agent running inside WSL before invoking wslgit, there is no way to use ssh-agent info from wslgit.

It would be nice I can use existing SSH_AUTH_SOCK inside WSL.

**Comment by andy-5** [comment] 2018-01-20 10:46
It should work just fine, however a few conditions need to be fullfilled:

1.  The ssh-agent must start automatically with bash, because wslgit opens a new bash, with a new environment. To do so, you can put something like this into your `.bashrc`:

    ```bash
    # Start ssh agent
    if ! pgrep -u "$USER" ssh-agent > /dev/null; then
        ssh-agent > ~/.ssh-agent-env
    fi
    # or load existing ssh-agent environment
    if [[ "$SSH_AGENT_PID" == "" ]]; then
        eval "$(<~/.ssh-agent-env)" > /dev/null
    fi
    ```

2.  There must be no additional output (like "Agent pid XXX") when starting bash, the above snippet also handles this.

3.  You cannot enter a passphrase when VS Code runs wslgit, therefore, your SSH key must already be added to the ssh-agent (or you use a SSH key without a passphrase). You can add your key with `ssh-add`.

If these conditions are fullfilled, pushing and pulling from VS Code should use the SSH key added to ssh-agent.

Does this work for you?

**Comment by diablodale** [comment] 2018-02-02 17:25
Yes, the conversation above.

Going one step further meta, I added GPG and gpg-agent (enables GPG signing in GIT + includes some ssh-agent functionality) instead of ssh-agent. These additions of mine and the ever fantastic `nvm` made my .bashrc execution time unacceptably slow for use with `wslgit` since every git command is a separate launch of bash and execution of `.bashrc` using the `-ic` option.

To greatly speed things, I took the approach of
1. Putting the launch of my daemons like ssh-agent, gpg-agent, dirmngr in my .profile
2. Put the set of my SSH_AUTH_SOCK, GPG_AGENT_INFO, etc. env variables using `pgrep` at the top of `.bashrc` before the check for the interactive flag
3. Put an `unset BASH_ENV` at the top of `.bashrc` to prevent it from being loaded twice when calling `bash -c xxxxx`. This may/not be expected behavior https://github.com/Microsoft/WSL/issues/2897
4. Changed/compiled wslgit code to remove the `-i` flag. From other issues here in the wslgit repo, the only reason for that flag is to load `.bashrc`. Therefore...
5. In Windows, set two environment variables `WSLENV=BASH_ENV` and `BASH_ENV=~/.bashrc`. This functionality is available in [Windows build 17063](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/). This might be able to be replaced with Rust code below.

This allows my non-interactive usage (only `-c`) to run only the first part of my .bashrc when it is a non-interactive scenario like with wslgit. Now my use of wslgit is quite fast in VS Code.

The two Windows environment variables of step 5 above can perhaps be replaced with some Rust code like the following
```rust
let git_proc = Command::new("bash")
        .env("BASH_ENV", "~/.bashrc")
        .arg("-c")
        .arg(&git_cmd)
        ...
```

**Comment by andy-5** [comment] 2018-02-02 19:30
Interesting idea. If I understand correctly, the Rust solution sketched at the end does not require any changes for current users of wslgit (as `.bashrc` is still loaded) but would allow to check for the `-i` flag in `.bashrc` to skip some initialization only required for a login shell (not for git).

Have you tested the Rust implementation? I would happily accept a pull request if this works as expected.

**Comment by diablodale** [comment] 2018-02-02 23:39
You wrote "...required for a login shell". Nothing in wslgit or my patch is concerned with login shells. Login shells are created when something launches bash with the `-l` option. FYI, this login option can be combined with command and/or interactive and/or both. For example `-lc` or `-li` or `-lic`. You can combine the options on the same dash - and on some platform versions it is recommended to combine them due to bash bugs on those platforms.

What **_does change_** is the behavior for interactive shells. This are launched with the `-i` option. It is likely that most users have not set the BASH_ENV variable. Therefore, for WSLGit v0.50 which uses the `-ic` option

1. bash runs
2. Since it is not a login shell, `.profile` and `.bash_profile` are _**not loaded**_
3. bash loads `.bashrc` because of the `-i` option
4. the default .bashrc with WSL has code in it which looks for the `-i` option. Since WSLgit used `-i`, bash runs the entire .bashrc file.

The approach I am currently using (its only been a day) slightly changes behavior.

1. bash runs
2. bash loads `.bashrc` due to the BASH_ENV setting.
3. Since it is not a login shell, `.profile` and `.bash_profile` are _**not loaded**_.  
_Notice the order of (2) and (3) are swapped, but since these files are not run, it doesn't matter._
4. the default .bashrc with WSL has code in it which looks for the `-i` option. Since the patched WSLgit _did not use_ that option, it runs only the first part of the .bashrc file.

There are some scenarios where the .bashrc is loaded twice with the new approach. It seems to be an technically-correct yet unusual behavior. There is a discussion on this at the issue https://github.com/Microsoft/WSL/issues/2897.

* Fix 1 I write above. It requires a user to edit their .bashrc file if they want to reduce every possible delay.
* Fix 2 is to use `wsl.exe` instead of `bash.exe`. This fix can be done completely inside WSLgit. However, it requires a version of Windows 10 from mid-2017 since that is when `wsl.exe` was added. I believe requiring at least a mid-2017 Windows 10 is a non-issue given the types of users using WSLgit and that you already have code in WSLgit to work with 1709 (aka FCU)

Fix 2 removes the need for the BASH_ENV environment variable, removes the need to use shell_escape(), and slightly simplifies the argument handling.

I am running this patch now and it appears to be working. All my normal git workflows work and files with spaces in their names are handled. You can see the code at https://github.com/diablodale/wslgit/tree/no-i

**Comment by andy-5** [comment] 2018-02-05 11:41
Ah, yes, I somehow confused "login" and "interactive". Thanks for the clarification.

I think the Rust code alone does not work (at least, it did not in my short test). I guess the reason is that the specified environment does not apply to WSL. It should propably also set WSLENV accordingly, but as I understand it, this is currently only available in a insiders build.

However, I think the switch to `wsl.exe` is benefitial, as `bash.exe` seems to be deprecated (as noted [here](https://docs.microsoft.com/en-us/windows/wsl/reference)). Therefore, I think we will eventually need something along the lines of your change.

**Comment by diablodale** [comment] 2018-02-05 21:24
I believe your fail with the patch on a build before 17063 (e.g. FCU) is expected due to reading again https://github.com/Microsoft/WSL/issues/219 and [Env vars in 17063](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/). The only variable before build 17063 that could be passed between subsystems (WIN<->WSL) is `PATH`.

Agreed. We do need to set WSLENV at the same time. I thought more and I now believe we should be cautious. It is possible that a user sets the Windows environment variables `WSLENV=BASH_ENV` and/or `BASH_ENV=/my/crazy/file/to/load`. There are other *nix emulators like MinGW and Cygwin; both of which do use the BASH_ENV if present.

I there are four cases (combinations of WSLENV and BASH_ENV) that need to be considered and what WSLgit should do for each.

**_What are your opinions on the four possible cases?_**

### Case 1:  👎 no BASH_ENV,    👎 no WSLENV containing "BASH_ENV"

This is the default case. Even though the users of WSLgit are probably advanced users, I suspect the largest set of them will not have these two environment variables set. 

I suggest we match the behavior you have in today's WSLgit v0.50. That means it should launch a non-login interactive shell with a command to run. This means `wsl bash -ic <command>` or if you are not concerned with deprecation then `bash -ic <command>`.

I _almost_ suggest a non-login non-interactive shell. I'm a bit torn as going non-interactive can significantly speed up WSLgit depending on what the user does in .bashrc. However, there is likely one or more users that would consider not loading .bashrc by default a breaking change. Sometimes, change is good and backwards compatibility is dead tissue to cut off. To enable this in code: `BASH_ENV=~/.bashrc`, `WSLENV` is created/loaded and `BASH_ENV` appended to it

### Case 2:  👍 has a BASH_ENV,    👎 no WSLENV containing "BASH_ENV"

This could be a user who also uses MinGW or Cygwin and set their BASH_ENV to affect those environments. Both emulators copy all Windows environment variables and do not transform between slash and backslash. They don't mount drives as /mnt/x/path. Home directories are different. Given those behaviors, it is very unlikely that the value the user has set for BASH_ENV would work in WSL. In addition, the user has not set WSLENV which both directly/indirectly communicates that the user does not want the BASH_ENV value to be sent and used in WSL.

We should isolate WSLgit's behavior away from what the user is doing with BASH_ENV. I suggest we do the same as for case 1.

### Case 3:  👎 no BASH_ENV,    👍 has WSLENV containing "BASH_ENV"

This is likely a person that was trying ideas, testing, or tinkering. They might have removed one var but forgot the other. Since there is no value of BASH_ENV, it behaves like the WSLENV environment variable didn't have an entry for BASH_ENV.

Therefore, this *is* case 1.

### Case 4:  👍 has a BASH_ENV,    👍 has WSLENV containing "BASH_ENV"

This is me or another advanced user that wants to control what startup files are run. This user has explicitly taken action twice (two variables) and is responsible for their own setup, successes, and failures.

I suggest we launch a non-login non-interactive shell with a command to run. This means `wsl <command>`. We do not need to add/change any environment variables since they have already been set by the user.

**Comment by diablodale** [comment] 2018-02-06 02:06
FYI, I've updated my branch with the ideas directly above.
https://github.com/diablodale/wslgit/tree/no-i

**Comment by andy-5** [comment] 2018-02-06 08:03
That sounds reasonable, however I think there is still a chance that it might suprise users that already use wslgit and later configure `BASH_ENV` and `WSLENV` for some other reason (when it eventually becomes available in regular Windows builds).

Another alternative could be to not use the `BASH_ENV` and `WSLENV` variables at all.

Instead, we could introduce an environment variable like `WSLGIT_USE_INTERACTIVE_SHELL` on the Windows side to control how wslgit works. The default setting would be `true`. You would then just set `WSLGIT_USE_INTERACTIVE_SHELL=false` in Windows. No need to exchange or override any environment variables between Windows and WSL.

What do you think?

**Comment by diablodale** [comment] 2018-02-06 13:17
While your scenario is a possible case, I have no concern. Why?

* Take the small set of people that use WSLgit. This isn't an insult. I love and am using WSLgit - thank you. Rather, it is very niche tool. Using the github api, I looked at your release downloads  
`wslgit.exe      2018-01-11 =      217`  
`wslgit.exe      2017-12-18 =      201`  
`wslgit.exe      2017-11-08 =      153`  
`wslgit.exe      2017-07-27 =      96`  
`Total Downloads = 667`
* Of that small set, now take the set of people that upgrade their copy of WSLgit to a new version of WSLgit that supports this feature.
* Of that small set, now take the set of people that configure BASH_ENV and WSLENV in the needed way.
* Of that small set, now take the set of people that configure BASH_ENV to be something other than ~/.bashrc
* Of that small set, now take the set of people that have their .bashrc written in a way that this matters.
* Of that small set, now take the set of people that are surprised, don't read the docs, and/or can't fix this on their own.
* And do this all in the time period between now and when VS Code is updated to call WSL's git natively.

I suspect this is on the order of "doesn't matter". For any outliers, the install docs will write of this feature. The changelog mention it. And we can open an issue on this purely as a doc and close it resolved so people can later find it if they web search for "wslgit .bashrc isn't running loading being sourced etc."

If we implemented a new env variable like `WSLGIT_USE_INTERACTIVE_SHELL`, it is undiscoverable; no one could guess it. Therefore, it will never be used... except... by people that want the feature to control startupfile loading of WSLgit. Those people web search for this specific feature, proactively read the docs when they upgrade, search through issues, read changelog, etc. for that feature. Once those people do that, then they are the same people as I write above -> people searching/reading docs.

Reading -> How to use `WSLGIT_USE_INTERACTIVE_SHELL`  
vs.  
Reading -> How to use `BASH_ENV+WSLENV`.

The former can never be discovered or silently work as expected. It requires search/reading.  
The latter may silently work as expected. In minute cases, can diagnose with search/reading.

Personally, I prefer the silently working and easier discoverability.

**Comment by andy-5** [comment] 2018-02-08 09:20
Good points. While I usually don't like too much "magic", it makes sense to make it silently work if the environment varibles are explicitly set by the user.

I don't have much time to test this at the moment, so it may take a while until I include these changes.

**Comment by diablodale** [comment] 2018-02-08 14:52
I can make a PR if you want to go with my approach.  Then you can review/test at your leisure.
Should I do that?

**Comment by andy-5** [comment] 2018-03-07 19:15
I merged your pull request earlier today, so I'm closing this. Thanks for your contribution.

I additionally also added the `WSLGIT_USE_INTERACTIVE_SHELL` environment variable as a second method to use non-interactive bash. The main reason was that I could actually test it on my non-Insiders Windows build. Also, it is more explicit and slightly simpler to setup.

I also added a bit of documentation to the readme explaining this feature.

**Closed by andy-5** 2018-03-07 19:15 UTC
Labels: enhancement
