### ISSUE TITLE
fatal errors from 'git rev-parse --show-toplevel' due to slash translation

### ISSUE THREAD

**Issue by diablodale** [andy-5/wslgit#17] opened 2018-02-01 15:11 UTC
## Setup

Microsoft Windows [Version 10.0.17074.1002]
Visual Studio Code x64 version 1.19.3
Git for Windows x64 version 2.16.1.windows.1
WSL git version 0.50 with Ubuntu apt git 2.16.1

## Repro

1. Configure Git, wslgit, and VS Code as per instructions on git repro
2. Open VS Code
3. Open directory/repro
4. Edit a file in repro
5. Save file
6. Choose Menu View/Output
7. From pulldown on right of output windows, choose GIT
8. Look through all the git output.

## Result

Multiple instances of the following git command and then errors
```
git rev-parse --show-toplevel
fatal: Not a git repository (or any parent up to mount point /mnt)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

## Expected

No fatal errors in this scenarios

## Fix

This appears to be related to the transformation of `/` to `\` on data returning from WSL back to Windows. I isolated a curious difference.

Using Git for Windows, the standard of VS Code with Git
```
c:\repos\wslgit\src>git rev-parse --show-toplevel
c:/repos/wslgit
```

Using WSLGit
```
c:\repos\wslgit\src>..\target\release\wslgit rev-parse --show-toplevel
c:\repos\wslgit
```

Notice that Git for Windows returns forward slashes while WSLGit returns backslashes.
I made the trivial changes in `main.rs` to return forward slashes so that the WSLGit output would match the Git for Windows output. With that change, I no longer receive the fatal git errors in VS Code.

## Questions

Before I submit a PR, I want to check with you and other users.

1. Why are backslashes being returned in the current codebase?
2. What are the specific scenarios that fail unless backslashes are used on return paths?

**Comment by andy-5** [comment] 2018-02-02 09:48
Thanks for your detailed report.

Initially, `wslgit` just returned the forward slashes from the Linux paths unmodified. However, they were changed to backslashes in 9f0ec68d3c33ddf89d5213c77f871a3cf5a94093 to fix #11.

It is possible that the behavior observed in #11 was actually a bug in VS Code itself, that has since been fixed in one of the patch releases to VS Code 1.19. Can you please check if #11 is still an issue with your change applied?

If everything works as expected, I would be happy to merge your pull request to restore the forward slashes. Otherwise, I think the errors shown in the log do not cause any harm (other than maybe slowing down the Git plugin), so we could keep the current behavior.

**Comment by diablodale** [comment] 2018-02-02 14:38
For now, I think this issue can be closed. Why? Because, today, I can't reproduce the fatal errors I wrote above using WSLgit v0.50. 

I am cautious because wslgit doesn't match windows git output. That's the primary git used with VSCode for Windows, that interface/slash-style has the most test coverage.

However, wslgit v0.50 is working now with the same VS Code I has yesterday (v1.19.3).
No need to flux code if everything is working. 🙂

It is possible that some work I was doing on my `.profile` and `.bashrc` introduced something which caused VS Code to not parse and by some magic forward slashes helped. 🧙‍♀️ That possibility and that I can't repro the problem today suggests it is something I am doing.

To answer your questions...
I have never seen the behavior of #11. Not with wslgit v0.50 or 0.50+my forward slash patch.

There are some git slash changes in VS Code v1.19.1 https://github.com/Microsoft/vscode/milestone/60?closed=1
And more git changes in VS Code v1.19.2 https://github.com/Microsoft/vscode/milestone/61?closed=1

**Comment by andy-5** [comment] 2018-02-02 18:59
I just checked, and I can reproduce the fatal errors if I open a file that is not inside a Git repository (this includes e.g. the VS Code Settings).  In that case the error is correct, as there is no Git repository to find.

So maybe you just had the Settings tab open?

Either way, I'm closing this as requested, as this does not seem to be a bug in `wslgit`.

**Closed by andy-5** 2018-02-02 18:59 UTC
