### ISSUE TITLE
Multiple WSL distro support

### ISSUE THREAD

**Issue by dixydo** [andy-5/wslgit#127] opened 2022-05-03 18:46 UTC
Hi! I have two Ubuntu WSL distro: Ubuntu and Ubuntu-20.04 for personal and working purposes respectively.
I set git executable in PhpStorm as `C:\Users\yevhe\bin\wslgit.exe` and git integration works fine with Ubuntu, but not with Ubuntu-20.04. It returns error `Error updating changes:  not a git repository (or any of the parent directories): .git`

Is it possible to get both of them working properly? If yes — how?

UPD: I have tried to download source code, replace `Ubuntu-20.04` with `Ubuntu` and compile two different versions, but still no luck.

**Comment by carlolars** [comment] 2022-07-13 19:35
The problem is that `wslgit` always use the default wsl, so when accessing the filesystem from windows on another wsl instance the paths will translate to a Unix-path that exists on the other wsl instance, but `wslgit` will then run in the default instance where that path likely doesn't exist.

I'll push a PR soon that should make it possible to use wslgit with multiple distros, you just have to make sure git/ssh is setup correctly in all distros you intend to access repos in :)

**Comment by andy-5** [comment] 2022-07-14 10:16
@dixydo There is now an alpha build available with the changes from @carlolars : 
https://ci.appveyor.com/project/andy-5/wslgit/build/artifacts

Does this work for your use case?

**Comment by dixydo** [comment] 2022-07-14 10:21
@andy-5 Thank you! Unfortunately I haven't possibility to test it right now as I'he already switched to single distro and route ssh config to repos manually to be able use  your tool. I will try to test it on weekend.

**Comment by andy-5** [comment] 2022-12-30 06:11
The changes have no been released as `wslgit` v1.2.0.

**Closed by andy-5** 2022-12-30 06:11 UTC
