### ISSUE TITLE
VSCode 1.18.1 and wslgit

### ISSUE THREAD

**Issue by riula** [andy-5/wslgit#10] opened 2017-12-08 20:58 UTC
Running Windows 10 with the Fall Creators update, removed the password requirement as per the documentation, and VSCode sort knows a version control system is in place, but it looks broken, and files are never flagged as dirty, and git blame doesn't work. 

Is this potentially because the path to my files contains a space in it?

**Comment by andy-5** [comment] 2017-12-11 09:26
Filenames with spaces should work just fine. Are changed files listed correctly after manually clicking the "Refresh" button? If so, then this is most likely due to some git command waiting for input.

For example, the VS Code Git plugin tries to do a `git fetch` initially, which might require authentication. You can check with `ps aux` in a WSL shell if there are any running git commands that did not finish. You can then try to manually run these commands in a WSL shell to see if they require any user input.

Also, after killing these hanging git processes, the Git plugin should work correctly and list changed files, etc.

Regarding `git blame`, is this a separate plugin? I cannot find this functionality in the standard Git plugin.

**Comment by riula** [comment] 2017-12-18 04:28
I don't see any change files listed. None of the actual git functionality is working unfortunately. I am seeing a lot of what is showing up in #11

`git blame` is indeed a separate plug in. I can deal with this separately.

**Comment by andy-5** [comment] 2017-12-18 09:19
Are you already on VS Code 1.19 now? I just uploaded a [new release](https://github.com/andy-5/wslgit/releases/tag/v0.4.0) which fixes #11.

Could you please try with the new version and report back?

**Comment by riula** [comment] 2017-12-18 21:59
Upgrade to both the newest version of VSCode (1.19) and wslgit. Still seeing the same thing.

<img width="395" alt="screenshot_2" src="https://user-images.githubusercontent.com/558331/34130120-4ad0a286-e40c-11e7-8cfb-be49a458aa48.png">

In this screen shot, i added a new line -- `const FURTHER = 50;` and its not showing as changed, and not VSCode is still behaving odd under Source Control.

**Comment by andy-5** [comment] 2017-12-19 07:33
Unfortunately, I can't reproduce your problem.

A few things to test:
- Post the output of running `ps aux` in WSL while VS Code is open (and showing the behaviour above)
- Try opening a new, empty git repository in VS Code (i.e. create a new folder and run `git init`)
- Start VS Code without any plugins by running `code --disable-extensions` on the command line
- Does running `wslgit.exe status` etc. work from the windows command line?

**Comment by riula** [comment] 2017-12-20 05:08
I tried everything you suggested. Still no luck. Running `wslgit.exe status` does work which I find odd. I've attached screenshots of my setup, and the results of the questions you asked. Hopefully it helps.

Results of `ps aux`
<img width="464" alt="screenshot_1" src="https://user-images.githubusercontent.com/558331/34192027-defb047e-e510-11e7-8d6a-3749aeef405d.png">

Results of new empty repository. Adding a simple single file. 
<img width="365" alt="screenshot_3" src="https://user-images.githubusercontent.com/558331/34192038-e715abb4-e510-11e7-805a-dc065900f809.png">

Settings. No Workspace settings exist. 
<img width="483" alt="screenshot_4" src="https://user-images.githubusercontent.com/558331/34192045-f4263260-e510-11e7-831f-be336b26b1e0.png">

**Comment by andy-5** [comment] 2017-12-20 08:32
I noticed you are using zsh. In #1 a user also had issues with a different shell.

Could it be that your shell writes something to stdout when a command is executed, i.e. a greeting message or something like that? Because this would prevent VS Code from correctly parsing the output of Git.

Can you post the output of the Git log from VS Code (View - Output - Choosing "Git" from the dropdown on the right). It should list all Git commands that VS Code tries to execute, and maybe also some errors.

What is the exact output if you run these commands manually from the command line, i.e.
```
cd git-repository
C:\tools\wslgit\wslgit.exe rev-parse --show-toplevel
```
This should just print the Windows path to the current Git repository, i.e. something like
```
c:\Users\someone\git-repository
```
Maybe you could also try to switch your shell back to bash.

**Comment by riula** [comment] 2017-12-20 18:31
You definitely seem to be on to something. I ran the command you suggested in `zsh` and `bash` and I did get the path in both cases, but differently. 

In zsh, I got it in this format
`/c/Users/someone/repo`

In bash, I got it in this format
`C:\Users\someone\repo

Upon making the change to `bash`, things have begun to work as expected save for one thing. I'm still seeing numerous `.Git` entries under Source Control Providers. Good news is one of those is correct and changes are now properly being flagged per file. 
<img width="203" alt="screenshot_5" src="https://user-images.githubusercontent.com/558331/34222531-7b3e61b2-e581-11e7-8b40-f948bac8946f.png">

**Comment by andy-5** [comment] 2017-12-21 08:10
Great! I wonder why it doesn't work with zsh. The zsh result is really strange, as the path inside WSL would be `/mnt/c/Users/...`, and `wslgit` translates that to `c:\Users\...` for Windows. I have no idea where this `/c/Users/...` format comes from.

How did you set zsh as your shell? AFAIK `chsh` does not work in WSL, does it? Do you `exec` it inside `.bashrc` or similar?

I also noticed these `.Git` entries occasionally. I see them for example then opening a file outside of the git repository, e.g. the user settings. I've already commited a possible fix for that, but did not yet release a new version of the executable.

**Comment by riula** [comment] 2017-12-21 15:43
Ah! 

You're seeing `/c/Users/...` because I'm using docker on windows from the ubuntu docker-ce client (our build scripts are written in bash and this was the only way to make it work). This required me to do a `mount --bind` from `/mnt/c` to simply `/c/` as docker mounts differently for windows as it does for ubuntu ([Setting up docker for WSL](https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly)

I got zsh working by simply creating a `.bash_profile`, and from within it I check that I have a `.bashrc` and if so, load it. Within the `.bashrc` I simply kick off `zsh`. This keeps everything consistent. 

Hope this helps!

**Comment by jupbarrera** [comment] 2017-12-21 17:19
I can confirm the same issue as @riula. Me too had to do a `mount --bind` from `/mnt/c` to simply `/c/`

**Comment by andy-5** [comment] 2017-12-22 07:44
Ah, that's interesting. Why does Git return paths for the different mount points (`/c/...` vs. `/mnt/c/...`) depending on the shell? I guess it has something to do with how the shells setup the environment.

In any case, `wslgit` currently explictly checks for paths starting with `/mnt/X`, where `X` is a Windows drive letter, and only converts those. All other paths/strings are passed unchanged. That explains why it does not work.

Maybe you can only start zsh in your `.bashrc` if there is a terminal attached, like this:
```
if [ -t 1 ]; then
  exec zsh
fi
```
This way you should be able to use zsh as your interactive shell, but use bash when called from other processes (like `wslgit`). However, I haven't tested this.

**Comment by andy-5** [comment] 2017-12-22 07:46
@jupbarrera Do you also use zsh as your shell? Does it work with bash? If so, can you try the solution posted above to only start zsh when a terminal is attached?

**Comment by riula** [comment] 2017-12-28 20:16
@andy-5 I actually use that exact set up in my `.bashrc` file. Unfortunately that doesn't work.

**Comment by andy-5** [comment] 2018-01-02 09:37
You could also try the following instead (from https://github.com/andy-5/wslgit/issues/1#issuecomment-319322075 ):
```bash
case $- in
    *c*) ;;
      *) exec zsh;;
esac
```

This checks if bash was called with the `-c` flag to directly execute a command (as done by `wslgit`) and uses bash for that case. For all other cases it executes zsh.

**Comment by wardpeet** [comment] 2018-01-05 21:36
I had the same issue at the top of my bashrc file I added 
```bash
if [[ $- == *"c"* ]]; then
  return;
fi;
```
all works like  a charm now!

**Comment by andy-5** [comment] 2018-01-11 08:27
Regarding the additional `.Git` entries, I've just released a [new version](https://github.com/andy-5/wslgit/releases/tag/v0.5.0) which hopefully fixes this. Can you please test with the latest release?

**Comment by andy-5** [comment] 2018-01-11 08:28
@wardpeet Great, thanks for sharing your solution.

@riula Does this also work for you?

**Comment by riula** [comment] 2018-01-13 20:43
@andy-5 so far seems much better. Even seems a lot faster. I felt like git would spin its tires for quite a bit before. I'll keep testing, and let you know if anything changes.

**Comment by andy-5** [comment] 2018-01-15 07:41
Great! I'm closing this issue now. Feel free to report any new problems (either here or in a new issue).

**Closed by andy-5** 2018-01-15 07:41 UTC
Labels: bug, needs feedback
