### ISSUE TITLE
Issue with bash not showing the commit details in Fork

### ISSUE THREAD

**Issue by andROYdified** [andy-5/wslgit#134] opened 2022-12-10 03:46 UTC
Just recently, I noticed that Fork was not showing the 'Commit/Changes/File Tree' pane, with an error message:
`/bin/bash: !--RevisionMessageEnd--; No such file or directory`

At first, I thought that the issue is with Fork, so I tried reinstall Fork, but the issue still persist.

The message disappeared only when I changed the Git Instance under preference to the default git that was include with the app.

So it's suggesting to me that the issue is with the wslgit symlink. 

![image](https://user-images.githubusercontent.com/79952179/206827575-5afc164e-aae3-4164-9544-6e06441b8f75.png)

I'm using Fork Version 1.80

Hope you can help me,

Thanks

**Comment by carlolars** [comment] 2022-12-12 07:21
Just updated to Fork 1.80 and got the same problem :/

**Comment by carlolars** [comment] 2022-12-12 08:22
The problem is that Fork changed one argument to `--pretty=format:%H±.%aN±.%aE±.%at±.%cN±.%cE±.%ct±.%P±.%B<!--RevisionMessageEnd-->`, and bash don't like unescaped `<`, `!` and `>`. I have implemented a fix that I'm testing now.

**Comment by sneakyvv** [comment] 2022-12-12 11:16
Same problem, did same steps, so I'm also assuming the issue is with wslgit

**Comment by sneakyvv** [comment] 2022-12-12 11:24
@carlolars seems like a promising fix. I tried to test it, but there's no release in your fork repo (yet), so I tried to build the package but it seems I'm missing a build script for the wslgit.exe file.
I guess I'll wait for your PR, unless there's something I can help with?

**Comment by DanPristupov** [comment] 2022-12-12 13:12
Hi! I'm sorry for making problems for you.

> The problem is that Fork changed one argument to `--pretty=format:%H±.%aN±.%aE±.%at±.%cN±.%cE±.%ct±.%P±.%B<!--RevisionMessageEnd-->`, and bash don't like unescaped `<`, `!` and `>`. I have implemented a fix that I'm testing now.

Yes, I confirm that. I didn't know that *particular* message could cause an issue.

**Comment by fabiomaggio** [comment] 2022-12-12 13:12
I'm having the same issue here...

**Comment by sneakyvv** [comment] 2022-12-12 14:41
@DanPristupov Is there a way to get the old release for Fork (< 1.80) somewhere temporarily? I didn't find a page for them on https://git-fork.com.

**Comment by DanPristupov** [comment] 2022-12-12 14:54
@sneakyvv 
You can download Fork 1.79 here (https://cdn.fork.dev/prerelease/ForkInstaller-1.79.exe), but you must disable the update. You must be very quick , otherwise Fork will check and install 1.80 already.

**Comment by andy-5** [comment] 2022-12-12 15:20
There is now a test build of `wslgit` with the fix by @carlolars available [for download](https://ci.appveyor.com/project/andy-5/wslgit/build/artifacts).

**Comment by sneakyvv** [comment] 2022-12-12 15:23
You guys are both stars! 🤘 

Can confirm it works on Fork 1.80 now 🎉

**Comment by andROYdified** [comment] 2022-12-12 16:11
Confirming that the test build works for Fork 1.80, 1.71 and 1.78 :)

You guys are awesome!

Thanks so much!

**Comment by andROYdified** [comment] 2022-12-12 16:13
> @sneakyvv You can download Fork 1.79 here (https://cdn.fork.dev/prerelease/ForkInstaller-1.79.exe), but you must disable automatic updates. You must be very quick , otherwise Fork will check and install 1.80 already.

This is the same thing I did. After downloading the installer, I disabled my WiFi, then proceed to setting it up (and most importantly disable automatic updates). :)

**Comment by DanPristupov** [comment] 2022-12-12 16:18
@carlolars @andy-5 will that be better if we change the separator to `--RevisionMessageEnd--` in the next update?

**Comment by MichalGow** [comment] 2022-12-13 14:29
> There is now a test build of `wslgit` with the fix by @carlolars available [for download](https://ci.appveyor.com/project/andy-5/wslgit/build/artifacts).

New wslgit (1.2.0-alpha3) doesn't work for me. Now I am getting fatal: unrecognized argument: --diff-merges=1

**Comment by andy-5** [comment] 2022-12-14 07:45
@MichalGow Yes, the `--diff-merges=1` flag seems to be a quite recent addition to git. I think you need at least version 2.31. There is nothing wslgit can do about that.

@DanPristupov I think there is no need to change the separator, now that wslgit can properly escape the special characters.

**Comment by jonbeebe** [comment] 2022-12-29 22:42
I also ran into this issue and the steps described here fixed it:

* Downloaded the test version of wslgit mentioned by @andy-5 
* Upgraded WSL git instance to latest

**Comment by andy-5** [comment] 2022-12-30 06:07
The changes to fix this are now released as `wslgit` v1.2.0.

**Closed by andy-5** 2022-12-30 06:07 UTC
