### ISSUE TITLE
Update to use wslpath?

### ISSUE THREAD

**Issue by scooley** [andy-5/wslgit#21] opened 2018-02-07 23:39 UTC
This may be a nice update for you:  
we have a new [wslpath tool](https://github.com/Microsoft/WSL/issues/2715) for the path munging and [a shared environment variable (WSLENV)](https://blogs.msdn.microsoft.com/commandline/2017/12/22/share-environment-vars-between-wsl-and-windows/) that uses wslpath to make the format right.

For drive mounting and networking mods, we also introduced [wsl.conf](https://blogs.msdn.microsoft.com/commandline/2018/02/07/automatically-configuring-wsl/)

Apologies for the doc lag

**Comment by andy-5** [comment] 2018-02-08 09:10
Thank you for these links.

There are already issues discussing the usage of `wslpath` (#12) and `WSLENV` (#16). So wslgit may eventually use these.
I did not know about `wsl.conf`.

I'm closing this, since this is mostly a duplicate of existing issues, but I appreciate the information.

**Closed by andy-5** 2018-02-08 09:10 UTC
Labels: duplicate, enhancement

**Comment by scooley** [comment] 2018-02-08 19:27
Awesome :).  Let me know if you run into issues.  I work on the product group building these tools and love early feedback.
